version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'git.put.your.host.here.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.put.your.host.here.com'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "your.smtp.server.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "gitlab@put.your.host.here.com"
        gitlab_rails['smtp_password'] = "your-smpt-super-password"
        gitlab_rails['smtp_domain'] = "put.your.host.here.com"
        gitlab_rails['gitlab_email_from'] = "gitlab@put.your.host.here.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = "peer"
        letsencrypt['enable'] = true
        letsencrypt['auto_renew'] = true
        letsencrypt['contact_emails'] = ['your-email@put.your.host.here.com']
        letsencrypt['auto_renew_hour'] = "12"
        letsencrypt['auto_renew_minute'] = "30"
        letsencrypt['auto_renew_day_of_month'] = "*/7"

        ### optimization https://docs.gitlab.com/omnibus/settings/memory_constrained_envs.html
        puma['worker_processes'] = 0
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
        gitlab_rails['env'] = {'MALLOC_CONF' => 'dirty_decay_ms:1000, muzzy_decay_ms:1000'}
        gitaly['env'] = {'LD_PRELOAD' => '/opt/gitlab/embedded/lib/libjemalloc.so', 'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000', 'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'}
        
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

